# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  gesture_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Gesture
  rule_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\Rule

  round_log_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - AppBundle\Entity\RoundLog

  round_service:
      class: AppBundle\Service\RoundService
      arguments:
        - "@gesture_repository"
        - "@rule_repository"

  round_logger_service:
        class: AppBundle\Service\RoundLogService
        arguments:
          - "@round_log_repository"

  gesture_service:
          class: AppBundle\Service\GestureService
          arguments:
            - "@gesture_repository"

  metrics_service:
            class: AppBundle\Service\MetricsService
            arguments:
              - "@doctrine.orm.entity_manager"
