<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GestureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestureRepository extends EntityRepository
{
}
