<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoundLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundLogRepository extends EntityRepository
{

    public function save( RoundLog $round_log )
    {
        $this->getEntityManager()->persist( $round_log );
        $this->getEntityManager()->flush();
    }
}
